apiVersion: 3
dataDisplay:
  textFormats:
    layout-orig-full: 
      method: layoutRich
      style:  orig
docs:
  docBase: '{docRoot}/syriac'
  docExt: ''
  docPage: ''
  docRoot: https://etcbc.github.io
  featurePage: 0_home
interfaceDefaults: {}
provenanceSpec:
  corpus: The ETCBC Syriac Corpus
  version: '0.1'
writing: hbo
typeDisplay:
  verse:
    label: '{verse}'
    template: '{verse}'
    verselike: true
  word:
    features: lex
